# Compile the submitted code, by open a terminal
# within the folder the code is in, and write "make all".

all:
	scanner1 scanner2 scanner3

scanner1:
	g++ -std=c++11 scanner_part1.cpp -o scanner1

scanner2:
	g++ -std=c++11 scanner_part2.cpp -o scanner2

scanner3:
	g++ -std=c++11 scanner_part3.cpp -o scanner3

