# Reference: https://piazza.com/class/kdrds5srlf6sr?cid=97 
# Compile the submitted code, by open a terminal within the folder the code is in, and write "make all".


all:
	server client

server: server.cpp
	g++ -std=c++11 server.cpp -o server

client: client.cpp
	g++ -std=c++11 client.cpp -o client

